name: Deploy to EC2 with PM2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build the project
        run: |
          npm --prefix ProjectVisualiser install
          npm --prefix ProjectVisualiser run build

      - name: Create SSH key file
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 400 ec2_key.pem

      - name: Verify SSH key file creation
        run: |
           ls -l ec2_key.pem
           cat ec2_key.pem

      - name: Add SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KNOWN_HOSTS }}" > ~/.ssh/known_hosts 

      - name: Backup current deployment
        env:
          KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          sudo ssh -i ec2_key.pem $USER@$HOST "cp -r /var/www/project /var/www/project-backup"

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          sudo scp -i ec2_key.pem -o StrictHostKeyChecking=no -r ./ProjectVisualiser/dist $USER@$HOST:/var/www/project

